[registry."registry-cache:5000"]
    http = true
    insecure = true
[registry."registry-mirror:5000"]
    http = true
    insecure = true
[registry."docker.io"]
    http = true
    insecure = true
    mirrors = ["registry-mirror:5000"]
